# Generated by Django 3.2.8 on 2021-11-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20211124_1147'),
        ('quizes', '0002_alter_quiz_quiz_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
