# Generated by Django 3.2.8 on 2021-11-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211124_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
