# Generated by Django 3.2.8 on 2021-11-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211124_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
