# Generated by Django 3.2.8 on 2021-11-24 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_userotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.SmallIntegerField()),
            ],
        ),
    ]
