# Generated by Django 3.2.8 on 2021-11-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userotp'),
        ('results', '0002_alter_useranswer_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
