# Generated by Django 3.2.8 on 2021-11-24 12:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0003_remove_useranswer_user_id'),
        ('user', '0007_delete_userlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
