# Generated by Django 3.2.8 on 2021-11-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211124_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
